2022-11-10 21:17:11,883 - execution started
2022-11-10 21:17:11,883 - reading input data file
2022-11-10 21:17:11,883 - failure in reading file
Traceback (most recent call last):
  File "/Users/umesh/PycharmProjects/scalableCap/src/load_data.py", line 25, in read_file
    with open(file_path, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: "'../input/dataset.txt'"
